### ISSUE TITLE
Fix occasional CMEs

### ISSUE THREAD

**Issue by gegy1000** [gegy1000/PokemonGO#13]

**Comment by gegy1000** [comment]
```java.util.ConcurrentModificationException
	at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966)
	at java.util.LinkedList$ListItr.next(LinkedList.java:888)
	at net.gegy1000.pokemon.client.event.ClientEventHandler.renderPokemonFeatures(ClientEventHandler.java:229)
	at net.gegy1000.pokemon.client.event.ClientEventHandler.onWorldRender(ClientEventHandler.java:205)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_33_ClientEventHandler_onWorldRender_RenderWorldLastEvent.invoke(.dynamic)```
